# -*- coding: utf-8 -*-
"""AI image Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFznzJBoNGevvMh9CaddxzQrxiKeY8xL
"""

!pip install -U diffusers transformers accelerate safetensors torch

import os
import torch
from diffusers import DiffusionPipeline
from tqdm import tqdm

))