# -*- coding: utf-8 -*-
"""AI image Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFznzJBoNGevvMh9CaddxzQrxiKeY8xL
"""

!pip install -U diffusers transformers accelerate safetensors torch

import os
import torch
from diffusers import DiffusionPipeline
from tqdm import tqdm

device = "cuda" if torch.cuda.is_available() else "cpu"

PROMPTS = [
    "A realistic portrait photo of a man, studio lighting",
    "A futuristic city at night, cyberpunk style",
    "A cat wearing a space suit, cinematic lighting",
    "An oil painting of a medieval knight",
    "A DSLR photo of a mountain landscape at sunrise"
]

MODELS = {
    "sd15": "rupeshs/LCM-runwayml-stable-diffusion-v1-5",
    "sdxl": "stabilityai/sdxl-turbo",
    "pixart": "PixArt-alpha/PixArt-Sigma-XL-2-1024-MS",
}

